stages:
    split_data:  
      cmd: python src/load_dataset.py
      deps:
        - src/load_dateset.py
        - src/utils/all_utils.py
        - config/config.yaml
        - data/with_crack
        - data/without_crack

      outs:
        - artifacts/data/test/with_crack
        - artifacts/data/test/without_crack
        - artifacts/data/train/with_crack
        - artifacts/data/train/without_data
        - artifacts/data/val/with_crack
        - artifacts/data/val/without_data


    prepare_model:
      cmd: python src/prepare_model.py
      deps:
        - src/prepare_model.py
        - src/utils/all_utils.py
        - config/config.yaml
        - src/utils/model.py
      outs:
        - artifacts/base_model/efficientnetb3.h5
        - artifacts/base_model/artifacts/base_model/updated_efficientdetb3_base_model.h5

    model_train:
      cmd: python src/model_train.py
      deps:
        - artifacts/data/test/with_crack
        - artifacts/data/test/without_crack
        - artifacts/data/train/with_crack
        - artifacts/data/train/without_data
        - artifacts/data/val/with_crack
        - artifacts/data
        - src/model_train.py
        - src/utils/all_utils.py
        - config/config.yaml
        - params.yaml
        - artifacts/base_model/updated_efficientdetb3_base_model.h5
      outs:
        - logs/fit/
        - artifacts/model_ckpt

  
