local_data_set_path: "C:/Users/kisho/Downloads/deep_learning_p1/scratch_detection/data/train"
artifacts:
  ARTIFACTS_DIR: artifacts
  data: data
  BASE_MODEL_DIR: base_model
  BASE_MODEL_NAME: efficientnetb3.h5
  UPDATED_BASE_MODEL_NAME: updated_VGG16_base_model.h5
